function keyboard_import_data = keyboard_importer(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COLEMAK = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a string array.
%
%  COLEMAK = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  colemak = importfile("C:\Users\taybe\Documents\MATLAB\Keyboard_Analysis\colemak.txt", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 30-Jul-2022 02:04:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["q", "w", "f", "p", "g", "VarName6", "j", "l", "u", "y", "VarName11", "VarName12"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["q", "w", "f", "p", "g", "VarName6", "j", "l", "u", "y", "VarName11", "VarName12"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["q", "w", "f", "p", "g", "VarName6", "j", "l", "u", "y", "VarName11", "VarName12"], "EmptyFieldRule", "auto");

% Import the data
keyboard_import_data = readmatrix(filename, opts);

end